### ISSUE TITLE
#D Administrative & User Frontend Meta Issue

### ISSUE THREAD

**Issue by cryptoquick** [Harryman/hashd#11]
Child issues will be created for these features as they are groomed and developed.

## Overview
- [ ] GraphQL Graphene Backend
- [ ] React Hooks Frontend
- [ ] Styles, UI/UX
- [ ] `hashd web -p 3000`

## Features
- [ ] Admin & User Authentication Portal (RSA-style PBKDF, stored and managed on frontend)
- [ ] Manage #D Peers (Links to other Onion-routed #D instances)
- [ ] User Block Header Explorer
- [ ] Service Management (Links to services running on that host)

**Comment by Harryman** [comment]
+1 for graphene graphql backend if we make this modular and well documented it can be used as a template or example app for people trying to build on #D building with that + react will give a us a bigger possible user base

Our first customer is ourselves we are trying build something that can get us paid and also be used to develop the software.

we are dogs, making dog food

**Comment by Harryman** [comment]
Admin and user auth. To be clear all of the clients will be talking to their own 'servers', what data they have on their server is proxied through the #D node which does authentication and data sync through gossip and subscriptions.
